### ISSUE TITLE
Validating a .yml rule

### ISSUE THREAD

**Issue by jdsika** [OpenSimulationInterface/osi-validation#64]
As a user I want to make sure that a custom rule set that has been created manually is parsed and checked for validity. The parser module is currently handling errors like a misspelled rule (without saying in which line the error is). This parser should be extended.

**Comment by masipp** [comment]
To add to this request we have the following usecase: 
We want to be able to gather requirements from a provider of a sensor fmu so that we are able to 
1. Check if the currently used environment simulation provides all information necessary for a specific FMU
2. Be able to approach the supplier of the environment simulation with new requirements

In order to make this possible the process of using the validator should be as userfriendly as possible to get high quality requirements. 

The validation of the yaml files should therefore tell the user where an error has occured.
In addition it would be great if the user is provided with a schema of what he is allowed to fill the yaml files with that can be included in an IDE for autocompletion.
